---
manual:Javascript
version:0
lang:zh
rawUrl:https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/URIError
---



这篇翻译不完整。请帮忙从英语[翻译这篇文章]42734 "")。






URIError 对象用来表示以一种错误的方式使用全局URI处理函数而产生的错误。


## 语法<a name="语法"></a>

```
new URIError([message[, fileName[, lineNumber]]])
```

### 参数<a name="参数"></a>
<dl><dt id=''>`message`</dt><dd>选填。易于理解的错误描述。</dd><dt id=''>`fileName`【非标准内联】</dt><dd>选填。包含造成异常的代码的文件名称。</dd><dt id=''>`lineNumber`【非标准内联】</dt><dd>选填。造成异常的代码行号。</dd></dl>
## 描述<a name="描述"></a>


当向全局 URI 处理函数传递一个不合法的URI时，URIError 错误会被抛出。


## 属性<a name="属性"></a>
<dl><dt id=''>[`URIError.prototype`]42735 "所有的 URIError 实例都继承自 URIError.prototype。 可以通过原型(prototype) 给所有的实例添加属性或者方法。")</dt><dd>允许向一个 URIError 对象添加额外的属性。</dd></dl>
## 方法<a name="方法"></a>


虽然全局 URIError 对象没有任何自己的方法，但是它能通过原型链继承一些方法。


## `URIError 实例`<a name="URIError_实例"></a>

### 属性<a name="属性_2"></a>
<dl><dt id=''>`URIError.prototype.constructor`</dt><dd>声明创建实例原型 (prototype) 的方法。</dd><dt id=''>[`URIError.prototype.message`]41987 "message 属性是有关错误信息，人类易读的（human-readable）描述。")</dt><dd>错误信息。虽然 ECMA-262 规范指出[`URIError`]40565 "URIError 对象用来表示以一种错误的方式使用全局URI处理函数而产生的错误。")应该提供其自己专属的`**message**`****属性，但是在[SpiderMonkey]42011 "")中，该属性继承自[`Error.prototype.message`]41987 "message 属性是有关错误信息，人类易读的（human-readable）描述。")</dd><dt id=''>[`URIError.prototype.name`]41988 "name 属性表示error类型的名称.初始值为"Error".")</dt><dd>错误名称。继承自[`Error`]10494 "通过Error的构造器可以创建一个错误对象。当运行时错误产生时，Error的实例对象会被抛出。Error对象也可用于用户自定义的异常的基础对象。下面列出了各种内建的标准错误类型。")。</dd><dt id=''>[`URIError.prototype.fileName`]41985 "fileName 属性包含引发此错误的文件的路径.")</dt><dd>产生该错误的代码所在文件的路径。 继承自[`Error`]10494 "通过Error的构造器可以创建一个错误对象。当运行时错误产生时，Error的实例对象会被抛出。Error对象也可用于用户自定义的异常的基础对象。下面列出了各种内建的标准错误类型。")。</dd><dt id=''>[`URIError.prototype.lineNumber`]41986 "lineNumber 属性的值为抛出错误的代码在其源文件中所在的行号。")</dt><dd>产生该错误的代码所在行的行号。继承自[`Error`]10494 "通过Error的构造器可以创建一个错误对象。当运行时错误产生时，Error的实例对象会被抛出。Error对象也可用于用户自定义的异常的基础对象。下面列出了各种内建的标准错误类型。")。</dd><dt id=''>[`URIError.prototype.columnNumber`]41984 "columnNumber属性包含引发此错误的文件行中的列号。")</dt><dd>产生该错误的代码所在列的列号。 继承自[`Error`]10494 "通过Error的构造器可以创建一个错误对象。当运行时错误产生时，Error的实例对象会被抛出。Error对象也可用于用户自定义的异常的基础对象。下面列出了各种内建的标准错误类型。")。</dd><dt id=''>[`URIError.prototype.stack`]42012 "此页面仍未被本地化, 期待您的翻译!")</dt><dd>堆栈记录。继承自[`Error`]10494 "通过Error的构造器可以创建一个错误对象。当运行时错误产生时，Error的实例对象会被抛出。Error对象也可用于用户自定义的异常的基础对象。下面列出了各种内建的标准错误类型。")。</dd></dl>

### 方法<a name="方法_2"></a>


虽然[`URIError`]40565 "URIError 对象用来表示以一种错误的方式使用全局URI处理函数而产生的错误。")的原型对象自身不包含任何方法，但是[`URIError`]40565 "URIError 对象用来表示以一种错误的方式使用全局URI处理函数而产生的错误。")的实例通过原型链(prototype chain)继承了一些方法。



## 示例<a name="示例"></a>

### 捕获一个`URIError 实例`<a name="捕获一个_URIError_实例"></a>

```
try {
  decodeURIComponent('%');
} catch (e) {
  console.log(e instanceof URIError); // true
  console.log(e.message);             // "malformed URI sequence"
  console.log(e.name);                // "URIError"
  console.log(e.fileName);            // "Scratchpad/1"
  console.log(e.lineNumber);          // 2
  console.log(e.columnNumber);        // 2
  console.log(e.stack);               // "@Scratchpad/2:2:3\n"
}
```

### 创建一个`URIError 实例`<a name="创建一个_URIError_实例"></a>

```
try {
  throw new URIError('Hello', 'someFile.js', 10);
} catch (e) {
  console.log(e instanceof URIError); // true
  console.log(e.message);             // "Hello"
  console.log(e.name);                // "URIError"
  console.log(e.fileName);            // "someFile.js"
  console.log(e.lineNumber);          // 10
  console.log(e.columnNumber);        // 0
  console.log(e.stack);               // "@Scratchpad/2:2:9\n"
}
```

## 规范<a name="规范"></a>

规范 | 状态 | 注释 
[ECMAScript 3rd Edition (ECMA-262)<br></br><small>URIError</small>]42736 "") | Standard | 初始定义 
[ECMAScript 5.1 (ECMA-262)<br></br><small>URIError</small>]42737 "") | Standard |  
[ECMAScript 2015 (6th Edition, ECMA-262)<br></br><small>URIError</small>]42738 "") | Standard |  
[ECMAScript Latest Draft (ECMA-262)<br></br><small>URIError</small>]42739 "") | Draft |  


## 浏览器兼容<a name="浏览器兼容"></a>
[新的兼容性表格正在测试中<i></i>]3360 "")

 | <abbr>Desktop<i></i></abbr> | <abbr>Mobile<i></i></abbr> | <abbr>Server<i></i></abbr> 
 | <abbr>Chrome<i></i></abbr> | <abbr>Edge<i></i></abbr> | <abbr>Firefox<i></i></abbr> | <abbr>Internet Explorer<i></i></abbr> | <abbr>Opera<i></i></abbr> | <abbr>Safari<i></i></abbr> | <abbr>Android webview<i></i></abbr> | <abbr>Chrome for Android<i></i></abbr> | <abbr>Edge Mobile<i></i></abbr> | <abbr>Firefox for Android<i></i></abbr> | <abbr>Opera for Android<i></i></abbr> | <abbr>iOS Safari<i></i></abbr> | <abbr>Samsung Internet<i></i></abbr> | <abbr>Node.js<i></i></abbr> 
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  | 
Basic support | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>1 | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>4 | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes | <abbr>Full support</abbr>Yes 


### Legend<a name="Legend"></a>
<dl><dt id=''><abbr>Full support</abbr></dt><dd>Full support</dd></dl>


## 参见<a name="参见"></a>

* [`Error`]10494 "通过Error的构造器可以创建一个错误对象。当运行时错误产生时，Error的实例对象会被抛出。Error对象也可用于用户自定义的异常的基础对象。下面列出了各种内建的标准错误类型。")
* [`URIError.prototype`]42735 "所有的 URIError 实例都继承自 URIError.prototype。 可以通过原型(prototype) 给所有的实例添加属性或者方法。")
* [`decodeURI()`]40569 "decodeURI() 函数解码一个由encodeURI 先前创建的统一资源标识符（URI）或类似的例程。")
* [`decodeURIComponent()`]40570 "decodeURIComponent() 方法用于解码由 encodeURIComponent 方法或者其它类似方法编码的部分统一资源标识符（URI）。")
* [`encodeURI()`]39937 "encodeURI()  函数通过将特定字符的每个实例替换为一个、两个、三或四转义序列来对统一资源标识符 (URI) 进行编码 (该字符的 UTF-8 编码仅为四转义序列)由两个 "代理" 字符组成)。")
* [`encodeURIComponent()`]40571 "encodeURIComponent()是对统一资源标识符（URI）的组成部分进行编码的方法。它使用一到四个转义序列来表示字符串中的每个字符的UTF-8编码（只有由两个Unicode代理区字符组成的字符才用四个转义字符编码）。")



